### ISSUE TITLE
Connection issues in python script

### ISSUE THREAD

**Issue by Demophobie** [joscha82/wattpilot#31]
Hi, 

i have a problem with a python script. In the header i set:

```
wattpilotIP = "192.168.1.6"
wattpilotPassword = "*******"
solarwatt = wattpilot.Wattpilot(wattpilotIP,wattpilotPassword)
solarwatt.connect()
```

Then in a "while True:"-loop:

```
c=0
    while not solarwatt.connected and c<5:
        sleep(1)
        c=c+1
        print(c)
```
It works like a charm, but i have two problems:

1. sometimes it does not connect to the wattpilot when i start the script. The c-while loop ends and solarwatt.connected is false.
2. it looses connection in a running script (which connected succesfully in the beginning) when carConnected-status changes

I tried to add **solarwatt.connect()** in the loop (in case that solarwatt.connected is false), but then i get a error message:

```
Exception in thread Thread-3 (run_forever):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pathaa/.local/lib/python3.10/site-packages/websocket/_app.py", line 354, in run_forever
    raise WebSocketException("socket is already opened")
websocket._exceptions.WebSocketException: socket is already opened

```

I am a newb. Anyone who can help? Is there a reconnect command or something? All i need is a save connection or a possibility to reconnect.

btw: The wifi is 100%. The router is 1m next to the wallbox. I dont get it....

**Comment by kesdoka1131** [comment]
The error message you received indicates that there is an attempt to open a WebSocket connection that is already open. It appears that the code is attempting to create a new WebSocket connection while there is an existing connection that has not been closed.

To resolve this issue, you can either close the existing WebSocket connection before attempting to create a new one or modify your code to ensure that only one connection is created at a time.

You can also try to add some logging or debug statements in your code to trace the sequence of events that led to the error. This will help you to identify the root cause of the issue and find an appropriate solution.
