### ISSUE TITLE
What is the initial password and default IP in Hotspot mode?

### ISSUE THREAD

**Issue by MPW1412** [joscha82/wattpilot#38]
Hello and thanks for this cool project!

I'm trying to connect to a Wattpilot, that has been factory resetted with the RFID card.

What is the default ip? My client gets an IP address in 10.128.250.0/24. But the Wattpilot doesn't seem to respond to pings, so it's not trivial to find the host. And what is the initial password? Is it the “hotspot key“ or the ”V.code“? 

Best,
Matthias

**Comment by peterpoetzi** [comment]
Hi, the initial IP is 10.128.250.181 and the wattpilot should also answer pings.

The initial password is empty, and can only be set with the Solar.Wattpilot app, but on hotspot you never need a password.

**Comment by MPW1412** [comment]
Hey, thanks for the quick answer!

And how do I set an empty password? wattpilotshell terminates itself:

```code
$ wattpilotshell 
Traceback (most recent call last):
  File "/usr/local/bin/wattpilotshell", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/wattpilot/wattpilotshell.py", line 1185, in main
    Cfg.set(os.environ)
  File "/usr/local/lib/python3.10/dist-packages/wattpilot/wattpilotshell.py", line 1152, in set
    assert not d.required or d.val, f"{var.name} is not set!"
AssertionError: WATTPILOT_PASSWORD is not set!
```

**Comment by peterpoetzi** [comment]
I am not familiar with wattpilotshell, but I guess maybe setting any password will just work. You can also connect with the Fronius app first, and actually set a password which will the also allow you to connect over local network.

**Comment by MPW1412** [comment]
The Fronius app for Android is completly broken. I tried to just set the wifi on three different days now and it just hangs. I need to make it work with this project or by an iphone, where the app shall work.
